field: e2e175dc-940c-43a1-81e9-4c7f66b3abcb # Social Links
fieldLayouts:
  40cc323c-cea7-43f7-86f5-0108e4df1933:
    tabs:
      -
        elements:
          -
            fieldUid: 6b4668e1-0133-4ccb-9b3a-721579bede30 # Social Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6b4668e1-0133-4ccb-9b3a-721579bede30: # Social Link
    columnSuffix: jqqhoafn
    contentColumnType: text
    fieldGroup: null
    handle: socialLink
    instructions: 'Sets the Link of the Social Account.'
    name: 'Social Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: instagram
name: Instagram
sortOrder: 2
