columnSuffix: qfntgpep
contentColumnType: text
fieldGroup: f2146acb-9f63-4455-b09a-196eb45a967a # Globals
handle: blurb
instructions: 'Sets the brief information about me.'
name: Blurb
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
