columnSuffix: null
contentColumnType: string
fieldGroup: 713bea6a-abb5-4484-b5eb-959d38412ab0 # Common
handle: mainImage
instructions: 'Sets the Main Image for the entry.'
name: 'Main Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a45a67cd-434f-4af3-ae12-bf586c35b10a' # Skills
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an Image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:a79dfb9e-c492-4af5-8730-f31193d0aa80' # General
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:a45a67cd-434f-4af3-ae12-bf586c35b10a' # Skills
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
