columnSuffix: null
contentColumnType: string
fieldGroup: 713bea6a-abb5-4484-b5eb-959d38412ab0 # Common
handle: pageHero
instructions: 'Adds a Page Hero to the current page.'
name: 'Page Hero'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagehero}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
