dateModified: 1634841660
email:
  fromEmail: noreply@jdf.gg
  fromName: JDF.GG
  replyToEmail: null
  template: null
  transportSettings:
    apiKey: $MAILJET_USERNAME
    apiSecret: $MAILJET_PASSWORD
  transportType: bertoost\mailjet\adapters\MailjetAdapter
meta:
  __names__:
    2aca6222-666c-4808-9040-7edb70adf348: 'Show Portrait' # Show Portrait
    2df9990f-fd03-4062-a94e-54bc62219770: Skills # Skills
    2e626468-052d-451c-b098-dd2c9668ad99: Blurb # Blurb
    2ec415fb-ec08-4367-a878-9b3c2a90d9a2: 'Full Name' # Full Name
    4b4e3804-b260-4820-91e4-5d26ac41ead3: Date # Date
    4dbc622d-3fcb-48d2-85bc-004f013c1daf: Homepage # Homepage
    5a107168-3402-4c40-bd70-d17b79b5ee92: 'Social Link' # Social Link
    6b4668e1-0133-4ccb-9b3a-721579bede30: 'Social Link' # Social Link
    6c077996-407b-4e45-9ec7-87f3758a5ae7: GitHub # GitHub
    6cc1691c-5ab0-44a2-bc9b-875c4e8b03ce: 'Hero Title' # Hero Title
    8ab07e06-3e07-42a8-8ff2-6e337f13403e: Languages # Languages
    9afcaf93-1dda-4acc-9028-1b520c9f07a4: Instagram # Instagram
    12f9861d-3bfa-4229-baf2-56e678f793a1: 'Hero Subtitle' # Hero Subtitle
    34b8ab34-bc2c-40ac-9c67-2ab75223aac7: Description # Description
    35ee7e17-f0b1-49d9-922e-931308ab99a2: 'Page Hero' # Page Hero
    61f89291-f8dd-475c-8e09-9c8906651db0: Portfolio # Portfolio
    76a3448d-528f-4c02-8068-b2a308c39378: 'Page Hero' # Page Hero
    94e35eaa-0387-4a84-ba12-051cab6d895e: 'White CTA Button' # White CTA Button
    412f7c9b-03cc-44ee-9e3e-4e4ae24cde13: 'Yellow CTA Button' # Yellow CTA Button
    713bea6a-abb5-4484-b5eb-959d38412ab0: Common # Common
    805b1819-a87b-4382-844b-2c1016f34c01: Skills # Skills
    0899acf6-a4db-492e-807f-6f3e91528984: Portfolio # Portfolio
    972f7785-d4d7-4b5e-84af-8254485fa48e: LinkedIn # LinkedIn
    4157ad4c-c757-4eb6-8587-5f6eb92d8ef8: 'About Me' # About Me
    6094d928-e987-4f6f-8376-7b6d4ce4c990: 'Main Menu' # Main Menu
    56566f96-5328-4853-a18c-649e64551808: 'Portfolio Card Image' # Portfolio Card Image
    074357a9-3568-4cb1-adc4-f07f5abb80d5: Portfolio # Portfolio
    932110f8-8b86-43c8-abbd-a61a6be0ef48: 'Main Image' # Main Image
    45314284-71c8-4d9c-a877-a94c540e2b7c: 'Global Information' # Global Information
    a45a67cd-434f-4af3-ae12-bf586c35b10a: Skills # Skills
    a79dfb9e-c492-4af5-8730-f31193d0aa80: General # General
    a24758d6-f49c-4f8a-9ba9-6499abe62333: 'Featured Skills' # Featured Skills
    aab0faa2-0b14-4d45-8618-ea1ee2305e71: 'Social Link' # Social Link
    ae086db1-29c9-490e-8397-2e52dcfdc79e: Body # Body
    b59a6ea1-61a4-4561-82b7-c6d4ffd016f9: Homepage # Homepage
    bdfac6d7-bcb1-4583-9d67-59978f917570: Skill # Skill
    be4e21d9-8cd2-41e7-9946-db046bf245fc: Homepage # Homepage
    ce0f0347-3a5e-48e8-be12-e23f4e945afc: Twitter # Twitter
    ddce0eb4-c0a8-4fc3-8ca8-955c5b7d239d: 'Social Link' # Social Link
    e2e175dc-940c-43a1-81e9-4c7f66b3abcb: 'Social Links' # Social Links
    e53c970f-ed56-47e1-96a0-3dda647ec7d9: JDF.GG # JDF.GG
    e66dd847-b3c7-4e76-a8af-e6f385bd3084: 'Related Entries' # Related Entries
    e3111181-4916-45ab-a207-e957eb08d895: JDF.GG # JDF.GG
    eb69c6ee-88c1-4d59-8921-4d7089fcb384: 'Site Tags' # Site Tags
    ece0267b-3623-42c1-b4e6-98569850f83d: Project # Project
    f2146acb-9f63-4455-b09a-196eb45a967a: Globals # Globals
plugins:
  animate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      activateAnimate: '1'
      animateOptions:
        - fade
        - fade-up
        - fade-down
        - fade-left
        - fade-right
        - fade-up-right
        - fade-up-left
        - fade-down-right
        - fade-down-left
        - flip-up
        - flip-down
        - flip-left
        - flip-right
        - slide-up
        - slide-down
        - slide-left
        - slide-right
        - zoom-in
        - zoom-in-up
        - zoom-in-down
        - zoom-in-left
        - zoom-in-right
        - zoom-out
        - zoom-out-up
        - zoom-out-down
        - zoom-out-left
        - zoom-out-right
      defaultSettings:
        __assoc__:
          -
            - offset
            - 120
          -
            - delay
            - 0
          -
            - duration
            - 400
          -
            - easing
            - ease
          -
            - once
            - false
          -
            - mirror
            - false
          -
            - anchorPlacement
            - top-bottom
      delay: '0'
      duration: '400'
      easing:
        __assoc__:
          -
            - match
            - '0'
      easingOpts:
        - linear
        - ease
        - ease-in
        - ease-out
        - ease-in-out
        - ease-in-back
        - ease-out-back
        - ease-in-out-back
        - ease-in-sine
        - ease-out-sine
        - ease-in-out-sine
        - ease-in-quad
        - ease-out-quad
        - ease-in-out-quad
        - ease-in-cubic
        - ease-out-cubic
        - ease-in-quart
        - ease-out-quart
        - ease-in-out-quart
      fades:
        -
          __assoc__:
            -
              - effect
              - fade
            -
              - usage
              - 'data-aos="fade"'
        -
          __assoc__:
            -
              - effect
              - fade-up
            -
              - usage
              - 'data-aos="fade-up"'
        -
          __assoc__:
            -
              - effect
              - fade-down
            -
              - usage
              - 'data-aos="fade-down"'
        -
          __assoc__:
            -
              - effect
              - fade-left
            -
              - usage
              - 'data-aos="fade-left"'
        -
          __assoc__:
            -
              - effect
              - fade-right
            -
              - usage
              - 'data-aos="fade-right"'
        -
          __assoc__:
            -
              - effect
              - fade-up-right
            -
              - usage
              - 'data-aos="fade-up-right"'
        -
          __assoc__:
            -
              - effect
              - fade-up-left
            -
              - usage
              - 'data-aos="fade-up-left"'
        -
          __assoc__:
            -
              - effect
              - fade-down-right
            -
              - usage
              - 'data-aos="fade-down-right"'
        -
          __assoc__:
            -
              - effect
              - fade-down-left
            -
              - usage
              - 'data-aos="fade-down-left"'
      flips:
        -
          __assoc__:
            -
              - effect
              - flip-up
            -
              - usage
              - 'data-aos="flip-up"'
        -
          __assoc__:
            -
              - effect
              - flip-down
            -
              - usage
              - 'data-aos="flip-down"'
        -
          __assoc__:
            -
              - effect
              - flip-left
            -
              - usage
              - 'data-aos="flip-left"'
        -
          __assoc__:
            -
              - effect
              - flip-right
            -
              - usage
              - 'data-aos="flip-right"'
      offset: '120'
      slides:
        -
          __assoc__:
            -
              - effect
              - slide-up
            -
              - usage
              - 'data-aos="slide-up"'
        -
          __assoc__:
            -
              - effect
              - slide-down
            -
              - usage
              - 'data-aos="slide-down"'
        -
          __assoc__:
            -
              - effect
              - slide-left
            -
              - usage
              - 'data-aos="slide-left"'
        -
          __assoc__:
            -
              - effect
              - slide-right
            -
              - usage
              - 'data-aos="slide-right"'
      useCDN: '1'
      useDefaultSettings: ''
      useOnEveryElement: false
      zooms:
        -
          __assoc__:
            -
              - effect
              - zoom-in
            -
              - usage
              - 'data-aos="zoom-in"'
        -
          __assoc__:
            -
              - effect
              - zoom-in-up
            -
              - usage
              - 'data-aos="zoom-in-up"'
        -
          __assoc__:
            -
              - effect
              - zoom-in-down
            -
              - usage
              - 'data-aos="zoom-in-down"'
        -
          __assoc__:
            -
              - effect
              - zoom-in-left
            -
              - usage
              - 'data-aos="zoom-in-left"'
        -
          __assoc__:
            -
              - effect
              - zoom-in-right
            -
              - usage
              - 'data-aos="zoom-in-right"'
        -
          __assoc__:
            -
              - effect
              - zoom-out
            -
              - usage
              - 'data-aos="zoom-out"'
        -
          __assoc__:
            -
              - effect
              - zoom-out-up
            -
              - usage
              - 'data-aos="zoom-out-up"'
        -
          __assoc__:
            -
              - effect
              - zoom-out-down
            -
              - usage
              - 'data-aos="zoom-out-down"'
        -
          __assoc__:
            -
              - effect
              - zoom-out-left
            -
              - usage
              - 'data-aos="zoom-out-left"'
        -
          __assoc__:
            -
              - effect
              - zoom-out-right
            -
              - usage
              - 'data-aos="zoom-out-right"'
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.2
  freeform:
    edition: lite
    enabled: true
    licenseKey: P1NMPNP1X8J18SGDVEWZ2KB0
    schemaVersion: 3.3.2
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: lubricantjam@pm.me
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: ''
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: ''
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: tailwind.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: true
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: ''
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: true
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  mailjet:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: C1ZUJIJYTS69SKB24HUEETZ4
    schemaVersion: 1.0.21
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  upper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: solo
  live: true
  name: JDF.GG
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
