fieldLayouts:
  23f8a38f-3dc7-43c2-9337-202e4ee2b894:
    tabs:
      -
        elements:
          -
            fieldUid: 2ec415fb-ec08-4367-a878-9b3c2a90d9a2 # Full Name
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 4b4e3804-b260-4820-91e4-5d26ac41ead3 # Date
            instructions: ' '
            label: 'Date of Birth'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 2e626468-052d-451c-b098-dd2c9668ad99 # Blurb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4157ad4c-c757-4eb6-8587-5f6eb92d8ef8 # About Me
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb69c6ee-88c1-4d59-8921-4d7089fcb384 # Site Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2e175dc-940c-43a1-81e9-4c7f66b3abcb # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: globalInformation
name: 'Global Information'
sortOrder: 1
