defaultPlacement: end
enableVersioning: true
handle: skills
name: Skills
propagationMethod: all
siteSettings:
  e53c970f-ed56-47e1-96a0-3dda647ec7d9: # JDF.GG
    enabledByDefault: true
    hasUrls: true
    template: skills/_entry
    uriFormat: 'skills/{slug}'
type: channel
